---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: cluster-spot
    region: us-east-1

nodeGroups:
    - name: ng-1
      minSize: 1
      maxSize: 2
      instancesDistribution:
        maxPrice: 0.017
        instanceTypes: ["t2.small", "t2.medium"] # At least one instance type should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 95
        spotInstancePools: 1