---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: cluster-spot
    region: us-east-1
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']
nodeGroups:
    - name: ng-1
      minSize: 1
      maxSize: 2
      instancesDistribution:
        maxPrice: 0.017
        instanceTypes: ["t2.small", "t2.medium"] # At least one instance type should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 95
        spotInstancePools: 1
      iam:
        withAddonPolicies: # polices added to worker node role
          externalDNS: true # allows read/write to zones in Route53
          certManager: true # access to ACM
          albIngress: true # access to ALB