# restrict to changes to these domains
domainFilters:
  - dfDns
# descriptive text to show who created record
txtOwnerId: "externaldns"
aws:
  zoneType: public
  region: "us-east-1"
  roleArn: "dfServiceAccountArn"
serviceAccount:
  create: false
  name: "external-dns"
# fetch latest image from the source
image:
  registry: registry.opensource.zalan.do
  repository: teapot/external-dns
  tag: v0.7.3