kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev2
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["create", "delete","list","get","watch"]
- apiGroups: ["extensions","apps"]
  resources: ["deployments"]
  verbs: ["create", "delete","get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete","get", "list", "watch"]  
