apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: acme-route53-tls
  namespace: cert-manager
spec:
  secretName: acme-route53
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'dfDns'