apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-route53-tls
spec:
  secretName: acme-route53
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'dfDns'