apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dfEmail
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - "dfDns"
        # DNS Challenger
        dns01:
          route53:
            region: us-east-1
            hostedZoneID: dfHostedZoneID
            accessKeyID: dfAccessKeyID
            secretAccessKeySecretRef:
              name: iam-secret
              key: secret-access-key